//! Translates the desktop renderer's WGSL (crates/siglus_scene_vm/src/
//! render/shaders) into GLSL 4.60 for devkitPro's `uam`, one file per entry
//! point, so the Switch draws with the desktop's own shaders.
//!
//! ```text
//! siglus_switch_shaderc <wgsl dir> <out dir>
//! ```
//!
//! Bindings are fixed: textures to the units the Switch renderer binds
//! (`TEXTURE_UNITS`), uniform buffers to `UNIFORM_BLOCKS`.

use std::path::{Path, PathBuf};

use naga::back::glsl;

/// (WGSL file, entry point, stage, output name).
const ENTRY_POINTS: &[(&str, &str, naga::ShaderStage, &str)] = &[
    ("sprite.wgsl", "vs_sprite_2d", naga::ShaderStage::Vertex, "sprite_vsh"),
    ("sprite.wgsl", "fs_sprite_2d", naga::ShaderStage::Fragment, "sprite_fsh"),
    ("sprite.wgsl", "vs_mesh_static", naga::ShaderStage::Vertex, "mesh_vsh"),
    ("sprite.wgsl", "fs_mesh_unlit", naga::ShaderStage::Fragment, "mesh_fsh"),
    ("sprite.wgsl", "vs_shadow_static", naga::ShaderStage::Vertex, "shadow_vsh"),
    ("sprite.wgsl", "fs_shadow_map", naga::ShaderStage::Fragment, "shadow_fsh"),
    ("wipe.wgsl", "vs_main", naga::ShaderStage::Vertex, "wipe_vsh"),
    ("wipe.wgsl", "fs_main", naga::ShaderStage::Fragment, "wipe_fsh"),
    ("page_wipe.wgsl", "vs_main", naga::ShaderStage::Vertex, "page_vsh"),
    ("page_wipe.wgsl", "fs_main", naga::ShaderStage::Fragment, "page_fsh"),
    ("emote.wgsl", "vs_main", naga::ShaderStage::Vertex, "emote_vsh"),
    ("emote.wgsl", "fs_main", naga::ShaderStage::Fragment, "emote_fsh"),
];

/// Texture unit of each WGSL texture binding (group 0), per file. The
/// sampler of a texture comes with it (combined image-sampler).
const TEXTURE_UNITS: &[(&str, u32, u8)] = &[
    // sprite.wgsl: tex0..tex4 at 0, 2, 4, 6, 8; shadow at 10; tex5, tex6.
    ("sprite.wgsl", 0, 0),
    ("sprite.wgsl", 2, 1),
    ("sprite.wgsl", 4, 2),
    ("sprite.wgsl", 6, 3),
    ("sprite.wgsl", 8, 4),
    ("sprite.wgsl", 14, 5),
    ("sprite.wgsl", 16, 6),
    ("sprite.wgsl", 10, 7),
    // wipe.wgsl: under, current, next, mask.
    ("wipe.wgsl", 0, 0),
    ("wipe.wgsl", 2, 1),
    ("wipe.wgsl", 4, 2),
    ("wipe.wgsl", 6, 3),
    ("page_wipe.wgsl", 0, 0),
    ("emote.wgsl", 0, 0),
];

/// Uniform block of each WGSL uniform binding, per file.
const UNIFORM_BLOCKS: &[(&str, u32, u8)] = &[
    // VsUniform, BoneUniform.
    ("sprite.wgsl", 12, 0),
    ("sprite.wgsl", 13, 1),
    // WipeUniform.
    ("wipe.wgsl", 8, 0),
];

fn main() {
    let mut args = std::env::args_os().skip(1);
    let (Some(wgsl_dir), Some(out_dir)) = (args.next(), args.next()) else {
        eprintln!("usage: siglus_switch_shaderc <wgsl dir> <out dir>");
        std::process::exit(2);
    };
    let wgsl_dir = PathBuf::from(wgsl_dir);
    let out_dir = PathBuf::from(out_dir);
    std::fs::create_dir_all(&out_dir).expect("create output directory");
    let mut failed = false;
    for &(file, entry, stage, name) in ENTRY_POINTS {
        match translate(&wgsl_dir.join(file), file, entry, stage) {
            Ok(glsl) => {
                let path = out_dir.join(format!("{name}.glsl"));
                std::fs::write(&path, glsl).expect("write GLSL");
            }
            Err(error) => {
                eprintln!("{file} {entry}: {error}");
                failed = true;
            }
        }
    }
    if failed {
        std::process::exit(1);
    }
}

fn translate(path: &Path, file: &str, entry: &str, stage: naga::ShaderStage) -> Result<String, String> {
    let source = std::fs::read_to_string(path).map_err(|e| format!("read: {e}"))?;
    let module = naga::front::wgsl::parse_str(&source).map_err(|e| e.emit_to_string(&source))?;
    let info = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    )
    .validate(&module)
    .map_err(|e| format!("validate: {e:?}"))?;

    let mut binding_map = glsl::BindingMap::default();
    for &(f, binding, unit) in TEXTURE_UNITS.iter().chain(UNIFORM_BLOCKS) {
        if f == file {
            binding_map.insert(naga::ResourceBinding { group: 0, binding }, unit);
        }
    }
    let options = glsl::Options {
        version: glsl::Version::Desktop(460),
        writer_flags: glsl::WriterFlags::empty(),
        binding_map,
        zero_initialize_workgroup_memory: false,
    };
    let pipeline_options = glsl::PipelineOptions {
        shader_stage: stage,
        entry_point: entry.to_owned(),
        multiview: None,
    };
    let mut out = String::new();
    let mut writer = glsl::Writer::new(
        &mut out,
        &module,
        &info,
        &options,
        &pipeline_options,
        naga::proc::BoundsCheckPolicies::default(),
    )
    .map_err(|e| format!("glsl writer: {e}"))?;
    writer.write().map_err(|e| format!("glsl: {e}"))?;
    Ok(format!(
        "// Generated by platform/switch/shaderc from {file} ({entry}); do not edit.\n{out}"
    ))
}
